site_name: MyPythonModule
nav:
    - Home: index.md
    - algorithm: algorithm.md
    - nlp: nlp.md
    - collections: collections.md
    - common: common.md
    - crawler: crawler.md
    - datetime_helper: datetime_helper.md
    - dict: dict.md
    - encoding: encoding.md
    - functools: functools.md
    - json: json.md
    - list: list.md
    - math: math.md
    - number: number.md
    - pathlib: pathlib.md
    - str: str.md
    - unique_key: unique_key.md
    - winreg: winreg.md
    - zhnumber: zhnumber.md
    - zhouyi: zhouyi.md


theme: readthedocs